{% set name = "plateau" %}
{% set version = "4.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/plateau-{{ version }}.tar.gz
  sha256: 7dd6e4fa79e6054db9b090eace582f095fba0aa0fbac60a3b6ed59c45c598b34

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - attrs
    - click
    - dask-core !=2021.5.1,!=2021.6.0
    - decorator
    - msgpack-python >=0.5.2
    - minimalkv >=1.4.2
    - numpy !=1.15.0,!=1.16.0
    - pandas >=0.23.0,!=1.0.0
    - prompt-toolkit
    - pyarrow >=4
    - python >=3.8
    - pyyaml
    - simplejson
    - toolz
    - urlquote >=1.1.3
    - zstandard

test:
  imports:
    - plateau
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/plateau/
  license: MIT
  license_file: LICENSE.txt
  summary: A consistent table management library in Python. Flat files, flat land.

extra:
  recipe-maintainers:
    - IzerOnadimQC
    - DamianB-BitFlipper
    - xhochy
    - janjagusch
